name: contexts-example
on:
  push:
  pull:
jobs:
  use-contexts:
    strategy:
      matrix:
        greeting: [Hello, Howdy, Hey]
    runs-on: ubuntu-latest
    steps:
      -
        name: Print greeting
        run: echo $GREETING
        env:
          GREETING: ${{ matrix.greeting }}
      -
        name: Do work with a secret
        run: ./workRequiringASecret.sh
        env:
          A_SECRET: ${{ secrets.A_SECRET }}
      -
        name: Run only for pulls
        if: ${{ github.event == "pull" }}
        run: echo "Triggered by a pull request"          
